services:
  img2lottie:
    image: docker.io/tolakang/img2lottie:latest
    container_name: img2lottie
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5177
    ports:
      - "5177:5177"
